CG-25 ci cd improvements (#192)

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -2,14 +2,10 @@
 FROM eclipse-temurin:21-jdk AS builder
 
 ARG SERVICE_NAME
-ARG COMMON_UTILS_VERSION
-ARG GPR_USER
-ARG GPR_TOKEN
+ARG APP_VERSION
 
 RUN test -n "$SERVICE_NAME" || (echo "ERROR: SERVICE_NAME build-arg is required" && exit 1)
-RUN test -n "$COMMON_UTILS_VERSION" || (echo "ERROR: COMMON_UTILS_VERSION build-arg is required" && exit 1)
-RUN test -n "$GPR_USER" || (echo "ERROR: GPR_USER build-arg is required" && exit 1)
-RUN test -n "$GPR_TOKEN" || (echo "ERROR: GPR_TOKEN build-arg is required" && exit 1)
+RUN test -n "$APP_VERSION" || (echo "ERROR: APP_VERSION build-arg is required" && exit 1)
 
 WORKDIR /build
 
@@ -18,10 +14,12 @@ COPY ${SERVICE_NAME}/gradlew ./
 COPY ${SERVICE_NAME}/gradle ./gradle
 COPY ${SERVICE_NAME}/build.gradle ${SERVICE_NAME}/settings.gradle ./
 
-RUN sed -i 's/\r$//' ./gradlew && \
-    chmod +x ./gradlew && \
+RUN sed -i 's/\r$//' ./gradlew && chmod +x ./gradlew
+
+RUN --mount=type=secret,id=gpr_user,env=GPR_USER \
+    --mount=type=secret,id=gpr_token,env=GPR_TOKEN \
     ./gradlew dependencies \
-      -PcommonUtilsVersion=${COMMON_UTILS_VERSION} \
+      -PcommonUtilsVersion=${APP_VERSION} \
       -PgprUser=${GPR_USER} \
       -PgprToken=${GPR_TOKEN} \
       --no-daemon || true
@@ -29,8 +27,10 @@ RUN sed -i 's/\r$//' ./gradlew && \
 # Исходники и сборка.
 COPY ${SERVICE_NAME}/src ./src
 
-RUN ./gradlew bootJar \
-      -PcommonUtilsVersion=${COMMON_UTILS_VERSION} \
+RUN --mount=type=secret,id=gpr_user,env=GPR_USER \
+    --mount=type=secret,id=gpr_token,env=GPR_TOKEN \
+    ./gradlew bootJar \
+      -PcommonUtilsVersion=${APP_VERSION} \
       -PgprUser=${GPR_USER} \
       -PgprToken=${GPR_TOKEN} \
       --no-daemon -x test && \
